title: Ethan J Cohen
description: Some of my thoughts on distributed systems, engineering leadership, the Internet of Things, and mobile app development.
theme: jekyll-theme-merlot
show_downloads: false
github:
  repository_url:
